FROM node:22.8.0-slim

ARG user=node
ARG uid=1000
ARG NODEMON_VERSION=3.1.7
ARG BACKEND_WORKDIR=/home/node/app

RUN apt-get update && apt-get install -y curl \
    && npm install -g nodemon@${NODEMON_VERSION} \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY start.sh /
RUN chmod +x /start.sh

RUN mkdir -p ${BACKEND_WORKDIR} \
    && chown -R $user:$user ${BACKEND_WORKDIR}

WORKDIR ${BACKEND_WORKDIR}

USER $user

EXPOSE 3000

CMD ["/bin/bash", "/start.sh"]